
jobs:
  - name: mohit-1
    type: manifest
    on_success:
      - script: echo 'this is a success'
    steps:
      - IN: box-nginx
      - IN: trigger-dv-man

  - name: mohit-2
    type: manifest
    steps:
      - IN: box-sn
      - IN: trigger-dv-man

  - name: coverage_sample_runCI
    type: runCI
    steps:
      - OUT: box-sn
