
jobs:
  - name: mohit-11
    type: manifest
    on_success:
      - script: echo 'this is a success'
    steps:
      - IN: box-nginx1
      - IN: trigger-dv-man1

  - name: mohit-21
    type: manifest
    steps:
      - IN: box-sn1
      - IN: trigger-dv-man1

  - name: sample_node_runCI
    type: runCI
    steps:
      - OUT: mohit-21
